version: "3"

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=disk
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_HOST=db
    command: bash -c "alembic upgrade head && uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "80:8000"
    depends_on:
      - db

volumes:
  postgres_data:
